### ISSUE TITLE
Missing Event Properties !

### ISSUE THREAD

**Issue by ankur-ships** [amplitude/Amplitude-ReactNative#136] opened 2022-08-13 10:09 UTC
Hello Amplitude Team, 

- I am using the amplitude-ReactNative library version 2.12.1 ! 
- When I log event with 3 properties, one of the properties out of 2 do not display immediately on the amplitude ui, user stream or data anywhere ! But after 12-24 hours when I try to look for it again, it appears. 
- This behaviour is very erratic and breaks our workflow. 
- We have observed this with multiple event_type and event_properties we have. It always takes more than 12 hours to see all events on the amplitude ui. Always 1 event property is missing.

Please help us.

**Comment by liuyang1520** [comment] 2022-08-13 19:17
Hi, @ankur-ships , thanks for reporting this! Based on your description, it sounds like a data processing issue after the ingestion. We can check with our data pipeline team next week for more details.

To help us quickly identify the problem, could you share us:
- whether this is a persisted issue, if yes, when did you notice this first time
- sample code used to init, set the event properties, and track
- sample event/raw event (redact PII) with "one of the properties out of 2 do not display immediately" and "takes more than 12 hours to see all events on the amplitude ui. Always 1 event property is missing", http payload is a plus if possible
- if possible, let us know your org id/project id with this issue. Note this is a public repo, if you are not comfortable to share here, feel free to contact our technical support

**Comment by ankur-ships** [comment] 2022-08-14 04:06
Thankyou for your replu @liuyang1520 :

- Yes it is a persistent issue. We were earlier using amplitude-js inside our react native app; and recently moved the react-native SDK. Ever since we have moved, we have observed this behaviour for all new events we add. Mind you, previous events show all properties perfectly but any new event we are adding, it always has at least 1 event property missing and shows us after a long wait time. 12+hours.

- Sample Code to Init, Set Event Properties and Track
`import {Amplitude, Identify} from '@amplitude/react-native'
const amplitude = Amplitude.getInstance()
const AmplitudeHelper = {
    init: () => { 
        amplitude.init(MY_KEY) 
        amplitude.setEventUploadPeriodMillis(10000)
        amplitude.setEventUploadMaxBatchSize(10)
        amplitude.setEventUploadThreshold(10)
    },
    logEvent: (eventName, data) => {
        try {
            amplitude.logEvent(eventName, data);
            console.log(eventName, data, "AMPLI_LOG")
        .........
`
Then inside my activity I import my Amplitude helper and invoke log event. 

- Sample Event / Raw Event
`{
  "$insert_id": "6270cef7-8e96-429c-8a20-dbb9e7b7d619",
  "$insert_key": "006a61434bac2acd172152d06c0d2c8d83#893",
  "$schema": 13,
  "_time": 1660297916310,
  "adid": null,
  "amplitude_attribution_ids": null,
  "amplitude_event_type": null,
  "amplitude_id": 443853178417,
  "app": 403606,
  "city": "Patna",
  "client_event_time": "2022-08-12 09:52:39.385000",
  "client_upload_time": "2022-08-12 09:52:49.452000",
  "country": "India",
  "data": {
    "group_first_event": {
    },
    "group_ids": {
    }
  },
  "data_type": "event",
  "device_brand": "samsung",
  "device_carrier": null,
  "device_family": "Samsung Phone",
  "device_id": "0069a411-f6f8-468d-a71d-b7d8eb70b910R",
  "device_manufacturer": "samsung",
  "device_model": "SM-M336BU",
  "device_type": "Samsung Galaxy M33 5G",
  "display_name": "payment_method_clicked",
  "dma": null,
  "event_id": 2295,
  "event_properties": {
    "referral_code": "53495748", <---- this was the event property not showing up initially but showing up after 12+ hours.
    "source": "payment_summary_page",
    "transaction_category_id": "bp-10"
  },
  "event_time": "2022-08-12 09:51:56.310000",
  "event_type": "payment_method_clicked",
  "global_user_properties": {
  },
  "group_properties": {
  },
  "groups": {
  },
  "idfa": null,
  "ip_address": <REDACTED>
  "is_attribution_event": false,
  "language": "English",
  "library": "amplitude-react-native/2.12.1",
  "location_lat": <REDACTED>,
  "location_lng": <REDACTED>,
  "os": "android 12",
  "os_name": "android",
  "os_version": "12",
  "partner_id": null,
  "paying": null,
  "plan": {
  },
  "platform": "Android",
  "region": "Bihar",
  "sample_rate": null,
  "server_received_time": "2022-08-12 09:51:06.377000",
  "server_upload_time": "2022-08-12 09:51:06.382000",
  "session_id": 1660288025709,
  "source_id": null,
  "start_version": "3.0.44-referral",
  "timeline_hidden": false,
  "user_creation_time": "2022-08-12 07:18:11.475000",
  "user_id": "36309-staging",
  "user_properties": {
    "GG User": true,
    "employerId": 577,
    "environment": "staging",
    "userId": 58546
  },
  "uuid": "4a7c8952-1a24-11ed-a6ba-db0339efc82a",
  "version_name": "3.0.44-referral"
}`
 
- Org ID: 98194, Project ID: 403606

**Comment by ankur-ships** [comment] 2022-08-14 13:14
Hello @liuyang1520 I can provide http payload too, can you tell me how to log it ? I am using the amplitude ReactNative sdk

**Comment by liuyang1520** [comment] 2022-08-14 16:01
@ankur-ships , thanks for sharing the details! I took a look at this, except I think the `setEventUploadThreshold` 10 is a little bit low and `setEventUploadPeriodMillis` 10000 is a little high, others are looking good IMO. And I don't think this is the issue, check the `Client Event Time`, `Client Upload Time`, `Server Upload Time`, `Server Received Time` on some events, they are pretty close. I think I will need to check with my team and pipeline team on Monday (PDT) to see what is the root cause.

For http payload, if you like to give it a try, check [this](https://stackoverflow.com/questions/33997443/how-can-i-view-network-requests-for-debugging-in-react-native), but I think these information above are sufficient now.

**Comment by ankur-ships** [comment] 2022-08-14 16:31
Thankyou @liuyang1520 ! I will anticipate a response. If you need any other information / details to help with this issue please let me know. Thankyou !

**Comment by ankur-ships** [comment] 2022-08-15 13:57
Hello @liuyang1520 , 
just trying to connect the dots. I observed this for another event. Both just fraction of seconds apart. One showed all the event properties 1 did not.

Raw Event of The One Which Shows
```
{
  "$insert_id": "1d4d2ef5-c2b5-4492-90b7-ae5bb0fc376b",
  "$row_source": "realtime",
  "$schema": 12,
  "_time": 1660541528506,
  "adid": null,
  "amplitude_attribution_ids": null,
  "amplitude_event_type": null,
  "amplitude_id": 444962630736,
  "app": 403606,
  "city": "Patna",
  "client_event_time": "2022-08-15 05:32:59.489000",
  "client_upload_time": "2022-08-15 05:33:05.078000",
  "country": "India",
  "data": {
    "group_first_event": {
    },
    "group_ids": {
    }
  },
  "device_brand": "samsung",
  "device_carrier": null,
  "device_family": "Samsung Phone",
  "device_id": "0069a411-f6f8-468d-a71d-b7d8eb70b910R",
  "device_manufacturer": "samsung",
  "device_model": "SM-M336BU",
  "device_type": "Samsung Galaxy M33 5G",
  "display_name": "referral_code_reminder",
  "dma": null,
  "event_id": 4096,
  "event_properties": {
    "action": "apply",
    "referral_code": "53495748",
    "source": "home_page"
  },
  "event_time": "2022-08-15 05:32:08.506000",
  "event_type": "referral_code_reminder",
  "group_properties": {
  },
  "groups": {
  },
  "idfa": null,
  "ip_address": "157.35.46.100",
  "is_attribution_event": false,
  "language": "English",
  "library": "amplitude-react-native/2.12.1",
  "location_lat": 24.8080016,
  "location_lng": 84.985167,
  "os": "android 12",
  "os_name": "android",
  "os_version": "12",
  "partner_id": null,
  "paying": null,
  "plan": {
  },
  "platform": "Android",
  "region": "Bihar",
  "sample_rate": null,
  "server_received_time": "2022-08-15 05:31:14.095000",
  "server_upload_time": "2022-08-15 05:31:14.100000",
  "session_id": 1660539763615,
  "start_version": "3.0.44-referral",
  "timeline_hidden": false,
  "user_creation_time": "2022-08-15 05:25:12.212000",
  "user_id": "36312-staging",
  "user_properties": {
    "GG User": true,
    "GT User": true,
    "employerId": 22538,
    "environment": "staging",
    "userId": 58549
  },
  "uuid": "7bae4bc4-1c5b-11ed-88df-712e2341b237",
  "version_name": "3.0.44-referral"
}
```

Raw Event of The One Which Does Not Show
```
{
  "$insert_id": "06d3d276-11cf-49ce-8bc4-b318fee167ba",
  "$row_source": "realtime",
  "$schema": 12,
  "_time": 1660541498670,
  "adid": null,
  "amplitude_attribution_ids": null,
  "amplitude_event_type": null,
  "amplitude_id": 444962630736,
  "app": 403606,
  "city": "Patna",
  "client_event_time": "2022-08-15 05:32:29.624000",
  "client_upload_time": "2022-08-15 05:32:39.710000",
  "country": "India",
  "data": {
    "group_first_event": {
    },
    "group_ids": {
    }
  },
  "device_brand": "samsung",
  "device_carrier": null,
  "device_family": "Samsung Phone",
  "device_id": "0069a411-f6f8-468d-a71d-b7d8eb70b910R",
  "device_manufacturer": "samsung",
  "device_model": "SM-M336BU",
  "device_type": "Samsung Galaxy M33 5G",
  "display_name": "referral_code_reminder",
  "dma": null,
  "event_id": 4092,
  "event_properties": {
    "action": "cancel",
    "source": "home_page"
  },
  "event_time": "2022-08-15 05:31:38.670000",
  "event_type": "referral_code_reminder",
  "group_properties": {
  },
  "groups": {
  },
  "idfa": null,
  "ip_address": "157.35.46.100",
  "is_attribution_event": false,
  "language": "English",
  "library": "amplitude-react-native/2.12.1",
  "location_lat": 24.8080016,
  "location_lng": 84.985167,
  "os": "android 12",
  "os_name": "android",
  "os_version": "12",
  "partner_id": null,
  "paying": null,
  "plan": {
  },
  "platform": "Android",
  "region": "Bihar",
  "sample_rate": null,
  "server_received_time": "2022-08-15 05:30:48.756000",
  "server_upload_time": "2022-08-15 05:30:48.759000",
  "session_id": 1660539763615,
  "start_version": "3.0.44-referral",
  "timeline_hidden": false,
  "user_creation_time": "2022-08-15 05:25:12.212000",
  "user_id": "36312-staging",
  "user_properties": {
    "GG User": true,
    "GT User": true,
    "employerId": 22538,
    "environment": "staging",
    "userId": 58549
  },
  "uuid": "6d0beefe-1c5b-11ed-93c4-ef181c8a87ce",
  "version_name": "3.0.44-referral"
}
```

**Comment by kevinpagtakhan** [comment] 2022-08-15 18:07
Hi @ankur-ships, thanks for reaching out to us regarding this issue. To clarify, when you say 1 out of 2 event properties don't show up until 12-24 hours later, does it show up later on the same event in the stream or a different one?

**Comment by BearMinimum98** [comment] 2022-08-15 23:05
hi @ankur-ships, does the event property show up in the event in user timelines (user stream)? the user timeline view is a near-raw view of the event after it is ingested by us.

**Comment by ankur-ships** [comment] 2022-08-16 02:42
Hello @kevinpagtakhan :
Yes it shows up later on the same event in the stream. Have attached the image of where I am looking for the event properties.
<img width="1101" alt="Screenshot 2022-08-16 at 8 12 05 AM" src="https://user-images.githubusercontent.com/9513861/184786996-b06646ce-e0ce-43d5-9bfc-d735aec73e67.png">

**Comment by ankur-ships** [comment] 2022-08-16 02:44
Hello @BearMinimum98 - 
I am not sure if I understood your question correctly. 
I am using : user lookup -> search user via id -> Event Stream 
For looking at amplitude events.

**Comment by BearMinimum98** [comment] 2022-08-16 21:28
Thanks Ankur. Could you let me know when this happens again ASAP so I can debug more? Our realtime data for that date has already been dropped

**Comment by ankur-ships** [comment] 2022-08-18 10:24
Hello @BearMinimum98 this happened with us again 
However this is a diff project and event name. But issue is same.
Missing event property : referral_code
`
{
  "$insert_id": "401026ac-b3f9-4add-ad48-01ae2e8f0050",
  "$row_source": "realtime",
  "$schema": 12,
  "_time": 1660812242740,
  "adid": null,
  "amplitude_attribution_ids": null,
  "amplitude_event_type": null,
  "amplitude_id": 448181113215,
  "app": 403605,
  "city": "Jakarta",
  "client_event_time": "2022-08-18 08:44:02.740000",
  "client_upload_time": "2022-08-18 08:44:08.079000",
  "country": "Indonesia",
  "data": {
    "group_first_event": {
    },
    "group_ids": {
    }
  },
  "device_brand": "vivo",
  "device_carrier": "Tsel-PakaiMasker",
  "device_family": "Vivo Phone",
  "device_id": "a1335880-6be1-4531-be75-3290122558a5R",
  "device_manufacturer": "vivo",
  "device_model": "vivo 1802",
  "device_type": "Vivo vivo 1802",
  "display_name": "referral_code_successful",
  "dma": null,
  "event_id": 18,
  "event_properties": {
    "source": "home_page"
  },
  "event_time": "2022-08-18 08:44:02.740000",
  "event_type": "referral_code_successful",
  "group_properties": {
  },
  "groups": {
  },
  "idfa": null,
  "ip_address": "182.3.37.85",
  "is_attribution_event": false,
  "language": "in",
  "library": "amplitude-react-native/2.13.0",
  "location_lat": -6.3022696,
  "location_lng": 107.1076537,
  "os": "android 8.1.0",
  "os_name": "android",
  "os_version": "8.1.0",
  "partner_id": null,
  "paying": null,
  "plan": {
  },
  "platform": "Android",
  "region": "Jakarta",
  "sample_rate": null,
  "server_received_time": "2022-08-18 08:44:09.132000",
  "server_upload_time": "2022-08-18 08:44:09.134000",
  "session_id": 1660812178703,
  "start_version": "4.0.0",
  "timeline_hidden": false,
  "user_creation_time": "2022-08-18 08:42:58.703000",
  "user_id": "148637",
  "user_properties": {
    "GG User": true,
    "Latitude": "null",
    "Longitude": "null",
    "employerId": 684,
    "environment": "new_production",
    "userId": 237936
  },
  "uuid": "eee314ef-1ed1-11ed-bddd-150aa26fa4f3",
  "version_name": "4.0.0"
}

`

**Comment by ankur-ships** [comment] 2022-08-18 11:14
Jesus Christ. 
Our workflow of amplitude events contained a lot of empty string event_properties. Eg: 'referral_code':''
Hence, the property was not showing up.

Is this a recent change ?

**Comment by BearMinimum98** [comment] 2022-08-18 17:22
@ankur-ships thanks! was `referral_code` empty or nullish on the raw event payload that you sent us?

**Comment by liuyang1520** [comment] 2022-08-18 17:45
@ankur-ships , if a key in the `event_properties` is empty/null value, this field will be dropped after ingestion. Can you find a recent example event that the `referral_code` is not showing up initially, but then shows up? Note that in the "Event Stream" page, the new events are streaming in, make sure the event is the same. Thanks!

**Comment by BearMinimum98** [comment] 2022-08-19 17:04
Our most recent batch run has finished and `referral_code` is still not showing up in the event. I'm inclined to believe this is because `referral_code` is not instrumented properly/was nullish and hence dropped during ingestion as intended.
<img width="502" alt="image" src="https://user-images.githubusercontent.com/1274230/185670705-687b7a2d-70b1-4754-ba25-2eeacf230600.png">

**Comment by ankur-ships** [comment] 2022-08-19 17:07
hello @BearMinimum98 @liuyang1520, 
yes; i can confirm i am able to replicate this behaviour if i send '' as the event property value.
I guess; when I came back and looked at the event with referral code, it must have been a different event :( 
my bad

**Comment by BearMinimum98** [comment] 2022-08-19 17:08
@ankur-ships great to hear! please close out this issue if it is no longer relevant.

**Comment by liuyang1520** [comment] 2022-08-19 17:15
@ankur-ships, glad that it has been figured out, thanks for validating this! Thank you @BearMinimum98 , @kevinpagtakhan for helping looking into the issue, going to close this issue.

**Closed by liuyang1520** 2022-08-19 17:15 UTC
