### ISSUE TITLE
TypeError: null is not an object (evaluating 'AmplitudeReactNative.setLibraryName')

### ISSUE THREAD

**Issue by emp3ror** [amplitude/Amplitude-ReactNative#69] opened 2021-04-16 08:30 UTC
TypeError: null is not an object (evaluating 'AmplitudeReactNative.setLibraryName')

Stack trace:
  node_modules/react-native/Libraries/LogBox/LogBox.js:148:8 in registerError
  node_modules/react-native/Libraries/LogBox/LogBox.js:59:8 in errorImpl
  node_modules/react-native/Libraries/LogBox/LogBox.js:33:4 in console.error
  node_modules/expo/build/environment/react-native-logs.fx.js:27:4 in error
  node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
  node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
  node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
  node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:9:32 in ErrorUtils.setGlobalHandler$argument_0
  node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
  node_modules/regenerator-runtime/runtime.js:293:29 in invoke
  node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
  node_modules/regenerator-runtime/runtime.js:154:27 in invoke
  node_modules/regenerator-runtime/runtime.js:164:18 in PromiseImpl.resolve.then$argument_0
  node_modules/react-native/node_modules/promise/setimmediate/core.js:37:13 in tryCallOne
  node_modules/react-native/node_modules/promise/setimmediate/core.js:123:24 in setImmediate$argument_0
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:130:14 in _callTimer
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:181:14 in _callImmediatesPass
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:441:30 in callImmediates
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:387:6 in __callImmediates
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:6 in __guard$argument_0
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:10 in __guard
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:4 in flushedQueue
  [native code]:null in flushedQueue
  [native code]:null in invokeCallbackAndReturnFlushedQueue
  ...

**Comment by yuhao900914** [comment] 2021-04-16 17:58
Hi @emp3ror,
Thanks for pointing out this issue.
Can you provide more info about which react-native version you are using, and how we can reproduce this?

**Comment by kelsonpw** [comment] 2021-04-17 17:48
It's very difficult to help with this minuscule amount of information.  I'd recommend providing more details in order to get assistance more effectively, but judging by the stack trace my thought is:

Expo managed projects do not support packages with native code (like this).

It looks like you are using expo, we do not support expo projects because we provide functionality through NativeModules (Java/Swift code).

**Comment by emp3ror** [comment] 2021-04-19 07:59
yes this is expo project, any work around, We tried using "expo-analytics-amplitude" package but it lacks many functionality like add

**Comment by kelsonpw** [comment] 2021-04-19 14:32
Perhaps submitting a PR to expo-analytics-amplitude.. Which functions is it missing?

**Comment by kelsonpw** [comment] 2021-04-19 14:37
expo-analytics-amplitude wraps our native sdks aswell so you could in theory submit a PR.

**Comment by emp3ror** [comment] 2021-04-19 14:57
let me try then :D

**Comment by kelsonpw** [comment] 2021-04-19 18:37
Gonna close this issue but would love to hear if how it goes submitting a PR to expo @emp3ror and happy to help in anyway I can

**Closed by kelsonpw** 2021-04-19 18:37 UTC
