### ISSUE TITLE
[!] Unable to determine Swift version for the following pods

### ISSUE THREAD

**Issue by DimaGavrushko** [amplitude/Amplitude-ReactNative#52] opened 2021-03-21 14:56 UTC
I got this issue when tried to install the library.

[!] Unable to determine Swift version for the following pods:

- `amplitude-react-native` does not specify a Swift version and none of the targets XXX integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

"@amplitude/react-native": "^2.0.9",
"react-native": "0.61.5",

**Comment by kelsonpw** [comment] 2021-03-21 15:35
Hey @DimaGavrushko can you give me some more details about your setup/machine?

**Comment by DimaGavrushko** [comment] 2021-03-21 18:54
> Hey @DimaGavrushko can you give me some more details about your setup/machine?

mac os Catalina (10.15.7)
Xcode 12.3

**Comment by kelsonpw** [comment] 2021-03-21 23:25
@DimaGavrushko the newest version `2.0.11` now explicitly declares swift version so that error should go away.

However when reproducing your issue locally, this didn't entirely resolve my build.  I also had to update the React-Core line in my podspec to:

```ruby
pod "React-Core", :path => "../node_modules/react-native/", :modular_headers => true
```

Another option is to declare `use_modular_headers!` globally at the top of your podfile.

I would recommend upgrading to the latest react native version you can (I know this can be difficult).  With 0.63 we require zero changes to the Podfile.

Please respond so that I can close this or help with additional issues.  Thank you for reporting!

**Comment by DimaGavrushko** [comment] 2021-03-22 06:53
> @DimaGavrushko the newest version `2.0.11` now [explicitly declares swift version](https://github.com/amplitude/Amplitude-ReactNative/blob/18a6ad9de65c22dc8995e6e91d9577e644f0b4fb/amplitude-react-native.podspec#L13) so that error should go away.
> 
> However when reproducing your issue locally, this didn't entirely resolve my build. I also had to update the React-Core line in my podspec to:
> 
> ```ruby
> pod "React-Core", :path => "../node_modules/react-native/", :modular_headers => true
> ```
> 
> Another option is to declare `use_modular_headers!` globally at the top of your podfile.
> 
> I would recommend upgrading to the latest react native version you can (I know this can be difficult). With 0.63 we require zero changes to the Podfile.
> 
> Please respond so that I can close this or help with additional issues. Thank you for reporting!


Thanks for the quick response. Those solutions allowed me to install the library, but when I tried to run the application, I got the bulk of errors/warnings. I am not sure which log exactly can help you.

The last lines of logs look like this:

![image](https://user-images.githubusercontent.com/22750804/111951197-6240cf80-8af4-11eb-81f4-ff3d3ef0be09.png)

Does it possible to provide a solution without upgrading RN?

**Comment by kelsonpw** [comment] 2021-03-22 08:11
@DimaGavrushko I never actually tried running the project, just gave it a shot and ran into the same issue.

Heres the fix:
- Open your `[project-name].xcodeproj` file in XCode
- Right Click your project name in the file navigator and then click New File, pick swift, it will then prompt you to creating a bridging headers file.  This is necessary to support swift in RN 0.61.5.

Source of this fix: https://stackoverflow.com/a/54586937

I'm pretty sure this will fix your problem, if you dont mind just let me know after trying if youre having any issues caused by this library

**Comment by DimaGavrushko** [comment] 2021-03-22 08:47
> @DimaGavrushko I never actually tried running the project, just gave it a shot and ran into the same issue.
> 
> 1. fix part one - xcode:
> 
> * Open your `[project-name].xcodeproj` file in XCode
> * Right Click your project name in the file navigator and then click New File, pick swift, it will then prompt you to creating a bridging headers file.  This is necessary to support swift in RN 0.61.5.
> * Source of this fix: https://stackoverflow.com/a/54586937
> 
> 1. fix part two - you will also need to make 4 changes to podfile:
> 
> * Add use_modular_headers! globally
> * Disable modular headers for DoubleConversion, Glog and Folly, like this PR [commit](https://github.com/kelsonpw/bug-reproduce-0.6.15/commit/c6e5a9d1e8e258f7c88e5a5d6f5bc8a04f9c6f0c#diff-281ded35b124f5160d0a57e47e521ee6f49f233933e091a0d33f3fd42a74abc8) for my test app:
> 
> I'm pretty sure this will fix your problem as it fixed it for me, if you dont mind just let me know after trying if youre having any issues caused by this library

Yes, it works. Thanks for your help!

**Comment by kelsonpw** [comment] 2021-03-22 09:05
Glad to hear it it @DimaGavrushko, if you have any feedback/issues/questions feel free to file another issue!  we always appreciate it.

**Closed by kelsonpw** 2021-03-22 09:05 UTC

**Comment by kelsonpw** [comment] 2021-03-22 15:01
cc @yuhao900914 for context
